dist: xenial
os: linux
language: node_js
node_js: lts/dubnium
cache: yarn
services:
  - docker

before_install:
  - git clone --depth=1 --branch=cpk-test https://github.com/gnosis/safe-relay-service.git

before_script:
  - yarn gunash --node-type $NODE_TYPE
  - cd safe-relay-service
  - docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
  - cd ..
  - yarn wait-port -t 10000 localhost:8000

after_script:
  - cd safe-relay-service
  - docker-compose logs web
  - docker-compose down
  - cd ..
  - yarn gunash stop

jobs:
  include:
  - name: Ganache with --noVMErrorsOnRPCResponse
    env: NODE_TYPE="ganache --noVMErrorsOnRPCResponse"

  - name: OpenEthereum
    env: NODE_TYPE=openethereum

after_success: yarn coverage
